You will be provided with a partial code base and an issue statement explaining a problem to resolve.

<issue>
Bad usability of exception messages when a file already exists in INTO OUTFILE
**Describe the issue**
```
milovidov-desktop :) SELECT * FROM numbers(10) INTO OUTFILE 'numbers.tsv'

SELECT *
FROM numbers(10)
INTO OUTFILE 'numbers.tsv'

Query id: 4512f761-2b36-4a25-9ccd-22982a17eb64

Ok.
Exception on client:
Code: 76. DB::Exception: Code: 76. DB::ErrnoException: Cannot open file numbers.tsv, errno: 17, strerror: File exists. (CANNOT_OPEN_FILE) (version 23.5.1.1). (CANNOT_OPEN_FILE)
```

1. It prints Ok, but then prints the exception message.
2. It prints `Code: 76.` and `Exception` twice.
3. It prints `CANNOT_OPEN_FILE` twice.
4. It does not suggest the usage of the `APPEND` syntax.
</issue>

I need you to solve the provided issue by generating a code fix that can be applied directly to the repository

Respond below:
