You will be provided with a partial code base and an issue statement explaining a problem to resolve.

<issue>
PROTOBUF_FIELD_NOT_REPEATED when ingesting from Kafka
**Describe what's wrong**

With a protobuf schema using a repeated message, setting up Kafka to use this schema to import into a table leads to the `PROTOBUF_FIELD_NOT_REPEATED` error. This does not happen when ingesting from `clickhouse-client`.

**Does it reproduce on recent release?**

Reproduced on 22.8.5.29.

**How to reproduce**

Using the 22.8 Docker image:
1. put `flow-3.proto` in `/var/lib/clickhouse/format_schemas`
2. create the Kafka table and one consumer, no need to get messages from Kafka

```protobuf
syntax = "proto3";
package decoder;

message FlowMessagev3 {
  uint64 TimeReceived = 2;
  repeated LargeCommunity DstLargeCommunities = 37;
  message LargeCommunity {
    uint32 ASN = 1;
    uint32 LocalData1 = 2;
    uint32 LocalData2 = 3;
  }
}
```

```sql
CREATE TABLE default.flows_3_raw
(
    `TimeReceived` DateTime CODEC(DoubleDelta, LZ4),
    `DstLargeCommunities.ASN` Array(UInt32),
    `DstLargeCommunities.LocalData1` Array(UInt32),
    `DstLargeCommunities.LocalData2` Array(UInt32)
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka:9092', kafka_topic_list = 'flows-v3', kafka_group_name = 'clickhouse', kafka_format = 'Protobuf', kafka_schema = 'flow-3.proto:FlowMessagev3', kafka_num_consumers = 1, kafka_thread_per_consumer = 1

CREATE TABLE default.flows
(
    `TimeReceived` DateTime CODEC(DoubleDelta, LZ4),
    `DstLargeCommunities.ASN` Array(UInt32),
    `DstLargeCommunities.LocalData1` Array(UInt32),
    `DstLargeCommunities.LocalData2` Array(UInt32)
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDDhhmmss(toStartOfInterval(TimeReceived, toIntervalSecond(25920)))
ORDER BY TimeReceived
TTL TimeReceived + toIntervalSecond(1296000)
SETTINGS index_granularity = 8192

CREATE MATERIALIZED VIEW default.flows_3_raw_consumer TO default.flows
AS SELECT * FROM default.flows_3_raw
```

Then, check `system.errors`. I get:

```
name:               PROTOBUF_FIELD_NOT_REPEATED
code:               437
value:              440
last_error_time:    2022-09-30 13:20:34
last_error_message: The field 'decoder.FlowMessagev3.LargeCommunity.ASN' must be repeated in the protobuf schema to match the column `ASN`
last_error_trace:   [171727226,366135675,366093641,366067646,366064173,366058066,366045826,366464972,366468882,364681438,337788230,337801743,364844405,364843206,364960586,364912827,364908569,364908061,364902892,337747165,337739135,333703256,333713718,333717100,172520264,172533085,140334772680201,140334771781939]
remote:             0
```

**Expected behavior**

No error in `system.errors`.

**Additional context**

It should be noted that sending messages work, including when they have a `DstLargeCommunity` field. They appear in the `flows` table without any issue.

cc @lesandie
</issue>

I need you to solve the provided issue by generating a code fix that can be applied directly to the repository

Respond below:
